/**
 * @fileoverview gRPC-Web generated client stub for feast.serving
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0
// source: feast/serving/ServingService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var feast_types_Value_pb = require('../../feast/types/Value_pb.js')
const proto = {};
proto.feast = {};
proto.feast.serving = require('./ServingService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.feast.serving.ServingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.feast.serving.ServingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.feast.serving.GetFeastServingInfoRequest,
 *   !proto.feast.serving.GetFeastServingInfoResponse>}
 */
const methodDescriptor_ServingService_GetFeastServingInfo = new grpc.web.MethodDescriptor(
  '/feast.serving.ServingService/GetFeastServingInfo',
  grpc.web.MethodType.UNARY,
  proto.feast.serving.GetFeastServingInfoRequest,
  proto.feast.serving.GetFeastServingInfoResponse,
  /**
   * @param {!proto.feast.serving.GetFeastServingInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.feast.serving.GetFeastServingInfoResponse.deserializeBinary
);


/**
 * @param {!proto.feast.serving.GetFeastServingInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.feast.serving.GetFeastServingInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.feast.serving.GetFeastServingInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.feast.serving.ServingServiceClient.prototype.getFeastServingInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/feast.serving.ServingService/GetFeastServingInfo',
      request,
      metadata || {},
      methodDescriptor_ServingService_GetFeastServingInfo,
      callback);
};


/**
 * @param {!proto.feast.serving.GetFeastServingInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.feast.serving.GetFeastServingInfoResponse>}
 *     Promise that resolves to the response
 */
proto.feast.serving.ServingServicePromiseClient.prototype.getFeastServingInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/feast.serving.ServingService/GetFeastServingInfo',
      request,
      metadata || {},
      methodDescriptor_ServingService_GetFeastServingInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.feast.serving.GetOnlineFeaturesRequest,
 *   !proto.feast.serving.GetOnlineFeaturesResponse>}
 */
const methodDescriptor_ServingService_GetOnlineFeatures = new grpc.web.MethodDescriptor(
  '/feast.serving.ServingService/GetOnlineFeatures',
  grpc.web.MethodType.UNARY,
  proto.feast.serving.GetOnlineFeaturesRequest,
  proto.feast.serving.GetOnlineFeaturesResponse,
  /**
   * @param {!proto.feast.serving.GetOnlineFeaturesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.feast.serving.GetOnlineFeaturesResponse.deserializeBinary
);


/**
 * @param {!proto.feast.serving.GetOnlineFeaturesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.feast.serving.GetOnlineFeaturesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.feast.serving.GetOnlineFeaturesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.feast.serving.ServingServiceClient.prototype.getOnlineFeatures =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/feast.serving.ServingService/GetOnlineFeatures',
      request,
      metadata || {},
      methodDescriptor_ServingService_GetOnlineFeatures,
      callback);
};


/**
 * @param {!proto.feast.serving.GetOnlineFeaturesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.feast.serving.GetOnlineFeaturesResponse>}
 *     Promise that resolves to the response
 */
proto.feast.serving.ServingServicePromiseClient.prototype.getOnlineFeatures =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/feast.serving.ServingService/GetOnlineFeatures',
      request,
      metadata || {},
      methodDescriptor_ServingService_GetOnlineFeatures);
};


module.exports = proto.feast.serving;

