/**
 * @fileoverview gRPC-Web generated client stub for feast.serving
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0
// source: feast/serving/TransformationService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.feast = {};
proto.feast.serving = require('./TransformationService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.feast.serving.TransformationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.feast.serving.TransformationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.feast.serving.GetTransformationServiceInfoRequest,
 *   !proto.feast.serving.GetTransformationServiceInfoResponse>}
 */
const methodDescriptor_TransformationService_GetTransformationServiceInfo = new grpc.web.MethodDescriptor(
  '/feast.serving.TransformationService/GetTransformationServiceInfo',
  grpc.web.MethodType.UNARY,
  proto.feast.serving.GetTransformationServiceInfoRequest,
  proto.feast.serving.GetTransformationServiceInfoResponse,
  /**
   * @param {!proto.feast.serving.GetTransformationServiceInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.feast.serving.GetTransformationServiceInfoResponse.deserializeBinary
);


/**
 * @param {!proto.feast.serving.GetTransformationServiceInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.feast.serving.GetTransformationServiceInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.feast.serving.GetTransformationServiceInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.feast.serving.TransformationServiceClient.prototype.getTransformationServiceInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/feast.serving.TransformationService/GetTransformationServiceInfo',
      request,
      metadata || {},
      methodDescriptor_TransformationService_GetTransformationServiceInfo,
      callback);
};


/**
 * @param {!proto.feast.serving.GetTransformationServiceInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.feast.serving.GetTransformationServiceInfoResponse>}
 *     Promise that resolves to the response
 */
proto.feast.serving.TransformationServicePromiseClient.prototype.getTransformationServiceInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/feast.serving.TransformationService/GetTransformationServiceInfo',
      request,
      metadata || {},
      methodDescriptor_TransformationService_GetTransformationServiceInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.feast.serving.TransformFeaturesRequest,
 *   !proto.feast.serving.TransformFeaturesResponse>}
 */
const methodDescriptor_TransformationService_TransformFeatures = new grpc.web.MethodDescriptor(
  '/feast.serving.TransformationService/TransformFeatures',
  grpc.web.MethodType.UNARY,
  proto.feast.serving.TransformFeaturesRequest,
  proto.feast.serving.TransformFeaturesResponse,
  /**
   * @param {!proto.feast.serving.TransformFeaturesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.feast.serving.TransformFeaturesResponse.deserializeBinary
);


/**
 * @param {!proto.feast.serving.TransformFeaturesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.feast.serving.TransformFeaturesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.feast.serving.TransformFeaturesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.feast.serving.TransformationServiceClient.prototype.transformFeatures =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/feast.serving.TransformationService/TransformFeatures',
      request,
      metadata || {},
      methodDescriptor_TransformationService_TransformFeatures,
      callback);
};


/**
 * @param {!proto.feast.serving.TransformFeaturesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.feast.serving.TransformFeaturesResponse>}
 *     Promise that resolves to the response
 */
proto.feast.serving.TransformationServicePromiseClient.prototype.transformFeatures =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/feast.serving.TransformationService/TransformFeatures',
      request,
      metadata || {},
      methodDescriptor_TransformationService_TransformFeatures);
};


module.exports = proto.feast.serving;

