// source: feast/serving/TransformationService.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.feast.serving.GetTransformationServiceInfoRequest', null, global);
goog.exportSymbol('proto.feast.serving.GetTransformationServiceInfoResponse', null, global);
goog.exportSymbol('proto.feast.serving.TransformFeaturesRequest', null, global);
goog.exportSymbol('proto.feast.serving.TransformFeaturesResponse', null, global);
goog.exportSymbol('proto.feast.serving.TransformationServiceType', null, global);
goog.exportSymbol('proto.feast.serving.ValueType', null, global);
goog.exportSymbol('proto.feast.serving.ValueType.ValueCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.serving.ValueType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.feast.serving.ValueType.oneofGroups_);
};
goog.inherits(proto.feast.serving.ValueType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.serving.ValueType.displayName = 'proto.feast.serving.ValueType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.serving.GetTransformationServiceInfoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.feast.serving.GetTransformationServiceInfoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.serving.GetTransformationServiceInfoRequest.displayName = 'proto.feast.serving.GetTransformationServiceInfoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.serving.GetTransformationServiceInfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.feast.serving.GetTransformationServiceInfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.serving.GetTransformationServiceInfoResponse.displayName = 'proto.feast.serving.GetTransformationServiceInfoResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.serving.TransformFeaturesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.feast.serving.TransformFeaturesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.serving.TransformFeaturesRequest.displayName = 'proto.feast.serving.TransformFeaturesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.serving.TransformFeaturesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.feast.serving.TransformFeaturesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.serving.TransformFeaturesResponse.displayName = 'proto.feast.serving.TransformFeaturesResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.feast.serving.ValueType.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.feast.serving.ValueType.ValueCase = {
  VALUE_NOT_SET: 0,
  ARROW_VALUE: 1
};

/**
 * @return {proto.feast.serving.ValueType.ValueCase}
 */
proto.feast.serving.ValueType.prototype.getValueCase = function() {
  return /** @type {proto.feast.serving.ValueType.ValueCase} */(jspb.Message.computeOneofCase(this, proto.feast.serving.ValueType.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.serving.ValueType.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.serving.ValueType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.serving.ValueType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.ValueType.toObject = function(includeInstance, msg) {
  var f, obj = {
    arrowValue: msg.getArrowValue_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.serving.ValueType}
 */
proto.feast.serving.ValueType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.serving.ValueType;
  return proto.feast.serving.ValueType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.serving.ValueType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.serving.ValueType}
 */
proto.feast.serving.ValueType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setArrowValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.serving.ValueType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.serving.ValueType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.serving.ValueType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.ValueType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes arrow_value = 1;
 * @return {string}
 */
proto.feast.serving.ValueType.prototype.getArrowValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes arrow_value = 1;
 * This is a type-conversion wrapper around `getArrowValue()`
 * @return {string}
 */
proto.feast.serving.ValueType.prototype.getArrowValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getArrowValue()));
};


/**
 * optional bytes arrow_value = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getArrowValue()`
 * @return {!Uint8Array}
 */
proto.feast.serving.ValueType.prototype.getArrowValue_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getArrowValue()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.feast.serving.ValueType} returns this
 */
proto.feast.serving.ValueType.prototype.setArrowValue = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.feast.serving.ValueType.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.feast.serving.ValueType} returns this
 */
proto.feast.serving.ValueType.prototype.clearArrowValue = function() {
  return jspb.Message.setOneofField(this, 1, proto.feast.serving.ValueType.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.feast.serving.ValueType.prototype.hasArrowValue = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.serving.GetTransformationServiceInfoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.serving.GetTransformationServiceInfoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.serving.GetTransformationServiceInfoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.GetTransformationServiceInfoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.serving.GetTransformationServiceInfoRequest}
 */
proto.feast.serving.GetTransformationServiceInfoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.serving.GetTransformationServiceInfoRequest;
  return proto.feast.serving.GetTransformationServiceInfoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.serving.GetTransformationServiceInfoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.serving.GetTransformationServiceInfoRequest}
 */
proto.feast.serving.GetTransformationServiceInfoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.serving.GetTransformationServiceInfoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.serving.GetTransformationServiceInfoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.serving.GetTransformationServiceInfoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.GetTransformationServiceInfoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.serving.GetTransformationServiceInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.serving.GetTransformationServiceInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.GetTransformationServiceInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    transformationServiceTypeDetails: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.serving.GetTransformationServiceInfoResponse}
 */
proto.feast.serving.GetTransformationServiceInfoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.serving.GetTransformationServiceInfoResponse;
  return proto.feast.serving.GetTransformationServiceInfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.serving.GetTransformationServiceInfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.serving.GetTransformationServiceInfoResponse}
 */
proto.feast.serving.GetTransformationServiceInfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {!proto.feast.serving.TransformationServiceType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransformationServiceTypeDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.serving.GetTransformationServiceInfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.serving.GetTransformationServiceInfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.GetTransformationServiceInfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTransformationServiceTypeDetails();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.serving.GetTransformationServiceInfoResponse} returns this
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TransformationServiceType type = 2;
 * @return {!proto.feast.serving.TransformationServiceType}
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.getType = function() {
  return /** @type {!proto.feast.serving.TransformationServiceType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.feast.serving.TransformationServiceType} value
 * @return {!proto.feast.serving.GetTransformationServiceInfoResponse} returns this
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string transformation_service_type_details = 3;
 * @return {string}
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.getTransformationServiceTypeDetails = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.serving.GetTransformationServiceInfoResponse} returns this
 */
proto.feast.serving.GetTransformationServiceInfoResponse.prototype.setTransformationServiceTypeDetails = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.serving.TransformFeaturesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.serving.TransformFeaturesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.serving.TransformFeaturesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.TransformFeaturesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    onDemandFeatureViewName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    project: jspb.Message.getFieldWithDefault(msg, 2, ""),
    transformationInput: (f = msg.getTransformationInput()) && proto.feast.serving.ValueType.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.serving.TransformFeaturesRequest}
 */
proto.feast.serving.TransformFeaturesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.serving.TransformFeaturesRequest;
  return proto.feast.serving.TransformFeaturesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.serving.TransformFeaturesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.serving.TransformFeaturesRequest}
 */
proto.feast.serving.TransformFeaturesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOnDemandFeatureViewName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    case 3:
      var value = new proto.feast.serving.ValueType;
      reader.readMessage(value,proto.feast.serving.ValueType.deserializeBinaryFromReader);
      msg.setTransformationInput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.serving.TransformFeaturesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.serving.TransformFeaturesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.serving.TransformFeaturesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.TransformFeaturesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOnDemandFeatureViewName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTransformationInput();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.feast.serving.ValueType.serializeBinaryToWriter
    );
  }
};


/**
 * optional string on_demand_feature_view_name = 1;
 * @return {string}
 */
proto.feast.serving.TransformFeaturesRequest.prototype.getOnDemandFeatureViewName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.serving.TransformFeaturesRequest} returns this
 */
proto.feast.serving.TransformFeaturesRequest.prototype.setOnDemandFeatureViewName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string project = 2;
 * @return {string}
 */
proto.feast.serving.TransformFeaturesRequest.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.serving.TransformFeaturesRequest} returns this
 */
proto.feast.serving.TransformFeaturesRequest.prototype.setProject = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ValueType transformation_input = 3;
 * @return {?proto.feast.serving.ValueType}
 */
proto.feast.serving.TransformFeaturesRequest.prototype.getTransformationInput = function() {
  return /** @type{?proto.feast.serving.ValueType} */ (
    jspb.Message.getWrapperField(this, proto.feast.serving.ValueType, 3));
};


/**
 * @param {?proto.feast.serving.ValueType|undefined} value
 * @return {!proto.feast.serving.TransformFeaturesRequest} returns this
*/
proto.feast.serving.TransformFeaturesRequest.prototype.setTransformationInput = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.feast.serving.TransformFeaturesRequest} returns this
 */
proto.feast.serving.TransformFeaturesRequest.prototype.clearTransformationInput = function() {
  return this.setTransformationInput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.feast.serving.TransformFeaturesRequest.prototype.hasTransformationInput = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.serving.TransformFeaturesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.serving.TransformFeaturesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.serving.TransformFeaturesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.TransformFeaturesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transformationOutput: (f = msg.getTransformationOutput()) && proto.feast.serving.ValueType.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.serving.TransformFeaturesResponse}
 */
proto.feast.serving.TransformFeaturesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.serving.TransformFeaturesResponse;
  return proto.feast.serving.TransformFeaturesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.serving.TransformFeaturesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.serving.TransformFeaturesResponse}
 */
proto.feast.serving.TransformFeaturesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = new proto.feast.serving.ValueType;
      reader.readMessage(value,proto.feast.serving.ValueType.deserializeBinaryFromReader);
      msg.setTransformationOutput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.serving.TransformFeaturesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.serving.TransformFeaturesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.serving.TransformFeaturesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.serving.TransformFeaturesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransformationOutput();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.feast.serving.ValueType.serializeBinaryToWriter
    );
  }
};


/**
 * optional ValueType transformation_output = 3;
 * @return {?proto.feast.serving.ValueType}
 */
proto.feast.serving.TransformFeaturesResponse.prototype.getTransformationOutput = function() {
  return /** @type{?proto.feast.serving.ValueType} */ (
    jspb.Message.getWrapperField(this, proto.feast.serving.ValueType, 3));
};


/**
 * @param {?proto.feast.serving.ValueType|undefined} value
 * @return {!proto.feast.serving.TransformFeaturesResponse} returns this
*/
proto.feast.serving.TransformFeaturesResponse.prototype.setTransformationOutput = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.feast.serving.TransformFeaturesResponse} returns this
 */
proto.feast.serving.TransformFeaturesResponse.prototype.clearTransformationOutput = function() {
  return this.setTransformationOutput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.feast.serving.TransformFeaturesResponse.prototype.hasTransformationOutput = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.feast.serving.TransformationServiceType = {
  TRANSFORMATION_SERVICE_TYPE_INVALID: 0,
  TRANSFORMATION_SERVICE_TYPE_PYTHON: 1,
  TRANSFORMATION_SERVICE_TYPE_CUSTOM: 100
};

goog.object.extend(exports, proto.feast.serving);
