// source: feast/storage/Redis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var feast_types_Value_pb = require('../../feast/types/Value_pb.js');
goog.object.extend(proto, feast_types_Value_pb);
goog.exportSymbol('proto.feast.storage.RedisKeyV2', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.storage.RedisKeyV2 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.feast.storage.RedisKeyV2.repeatedFields_, null);
};
goog.inherits(proto.feast.storage.RedisKeyV2, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.storage.RedisKeyV2.displayName = 'proto.feast.storage.RedisKeyV2';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.feast.storage.RedisKeyV2.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.storage.RedisKeyV2.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.storage.RedisKeyV2.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.storage.RedisKeyV2} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.storage.RedisKeyV2.toObject = function(includeInstance, msg) {
  var f, obj = {
    project: jspb.Message.getFieldWithDefault(msg, 1, ""),
    entityNamesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    entityValuesList: jspb.Message.toObjectList(msg.getEntityValuesList(),
    feast_types_Value_pb.Value.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.storage.RedisKeyV2}
 */
proto.feast.storage.RedisKeyV2.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.storage.RedisKeyV2;
  return proto.feast.storage.RedisKeyV2.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.storage.RedisKeyV2} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.storage.RedisKeyV2}
 */
proto.feast.storage.RedisKeyV2.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addEntityNames(value);
      break;
    case 3:
      var value = new feast_types_Value_pb.Value;
      reader.readMessage(value,feast_types_Value_pb.Value.deserializeBinaryFromReader);
      msg.addEntityValues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.storage.RedisKeyV2.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.storage.RedisKeyV2.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.storage.RedisKeyV2} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.storage.RedisKeyV2.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEntityNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getEntityValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      feast_types_Value_pb.Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional string project = 1;
 * @return {string}
 */
proto.feast.storage.RedisKeyV2.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.storage.RedisKeyV2} returns this
 */
proto.feast.storage.RedisKeyV2.prototype.setProject = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string entity_names = 2;
 * @return {!Array<string>}
 */
proto.feast.storage.RedisKeyV2.prototype.getEntityNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.feast.storage.RedisKeyV2} returns this
 */
proto.feast.storage.RedisKeyV2.prototype.setEntityNamesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.feast.storage.RedisKeyV2} returns this
 */
proto.feast.storage.RedisKeyV2.prototype.addEntityNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.feast.storage.RedisKeyV2} returns this
 */
proto.feast.storage.RedisKeyV2.prototype.clearEntityNamesList = function() {
  return this.setEntityNamesList([]);
};


/**
 * repeated feast.types.Value entity_values = 3;
 * @return {!Array<!proto.feast.types.Value>}
 */
proto.feast.storage.RedisKeyV2.prototype.getEntityValuesList = function() {
  return /** @type{!Array<!proto.feast.types.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, feast_types_Value_pb.Value, 3));
};


/**
 * @param {!Array<!proto.feast.types.Value>} value
 * @return {!proto.feast.storage.RedisKeyV2} returns this
*/
proto.feast.storage.RedisKeyV2.prototype.setEntityValuesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.feast.types.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.feast.types.Value}
 */
proto.feast.storage.RedisKeyV2.prototype.addEntityValues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.feast.types.Value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.feast.storage.RedisKeyV2} returns this
 */
proto.feast.storage.RedisKeyV2.prototype.clearEntityValuesList = function() {
  return this.setEntityValuesList([]);
};


goog.object.extend(exports, proto.feast.storage);
