// source: feast/core/ValidationProfile.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.feast.core.GEValidationProfile', null, global);
goog.exportSymbol('proto.feast.core.GEValidationProfiler', null, global);
goog.exportSymbol('proto.feast.core.GEValidationProfiler.UserDefinedProfiler', null, global);
goog.exportSymbol('proto.feast.core.ValidationReference', null, global);
goog.exportSymbol('proto.feast.core.ValidationReference.CachedProfileCase', null, global);
goog.exportSymbol('proto.feast.core.ValidationReference.ProfilerCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.core.GEValidationProfiler = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.feast.core.GEValidationProfiler, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.core.GEValidationProfiler.displayName = 'proto.feast.core.GEValidationProfiler';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.feast.core.GEValidationProfiler.UserDefinedProfiler, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.core.GEValidationProfiler.UserDefinedProfiler.displayName = 'proto.feast.core.GEValidationProfiler.UserDefinedProfiler';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.core.GEValidationProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.feast.core.GEValidationProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.core.GEValidationProfile.displayName = 'proto.feast.core.GEValidationProfile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.feast.core.ValidationReference = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.feast.core.ValidationReference.oneofGroups_);
};
goog.inherits(proto.feast.core.ValidationReference, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.feast.core.ValidationReference.displayName = 'proto.feast.core.ValidationReference';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.core.GEValidationProfiler.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.core.GEValidationProfiler.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.core.GEValidationProfiler} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.GEValidationProfiler.toObject = function(includeInstance, msg) {
  var f, obj = {
    profiler: (f = msg.getProfiler()) && proto.feast.core.GEValidationProfiler.UserDefinedProfiler.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.core.GEValidationProfiler}
 */
proto.feast.core.GEValidationProfiler.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.core.GEValidationProfiler;
  return proto.feast.core.GEValidationProfiler.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.core.GEValidationProfiler} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.core.GEValidationProfiler}
 */
proto.feast.core.GEValidationProfiler.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.feast.core.GEValidationProfiler.UserDefinedProfiler;
      reader.readMessage(value,proto.feast.core.GEValidationProfiler.UserDefinedProfiler.deserializeBinaryFromReader);
      msg.setProfiler(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.core.GEValidationProfiler.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.core.GEValidationProfiler.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.core.GEValidationProfiler} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.GEValidationProfiler.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfiler();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.feast.core.GEValidationProfiler.UserDefinedProfiler.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.core.GEValidationProfiler.UserDefinedProfiler.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.core.GEValidationProfiler.UserDefinedProfiler} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.toObject = function(includeInstance, msg) {
  var f, obj = {
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.core.GEValidationProfiler.UserDefinedProfiler}
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.core.GEValidationProfiler.UserDefinedProfiler;
  return proto.feast.core.GEValidationProfiler.UserDefinedProfiler.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.core.GEValidationProfiler.UserDefinedProfiler} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.core.GEValidationProfiler.UserDefinedProfiler}
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.core.GEValidationProfiler.UserDefinedProfiler.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.core.GEValidationProfiler.UserDefinedProfiler} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes body = 1;
 * @return {string}
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes body = 1;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.feast.core.GEValidationProfiler.UserDefinedProfiler} returns this
 */
proto.feast.core.GEValidationProfiler.UserDefinedProfiler.prototype.setBody = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional UserDefinedProfiler profiler = 1;
 * @return {?proto.feast.core.GEValidationProfiler.UserDefinedProfiler}
 */
proto.feast.core.GEValidationProfiler.prototype.getProfiler = function() {
  return /** @type{?proto.feast.core.GEValidationProfiler.UserDefinedProfiler} */ (
    jspb.Message.getWrapperField(this, proto.feast.core.GEValidationProfiler.UserDefinedProfiler, 1));
};


/**
 * @param {?proto.feast.core.GEValidationProfiler.UserDefinedProfiler|undefined} value
 * @return {!proto.feast.core.GEValidationProfiler} returns this
*/
proto.feast.core.GEValidationProfiler.prototype.setProfiler = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.feast.core.GEValidationProfiler} returns this
 */
proto.feast.core.GEValidationProfiler.prototype.clearProfiler = function() {
  return this.setProfiler(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.feast.core.GEValidationProfiler.prototype.hasProfiler = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.core.GEValidationProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.core.GEValidationProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.core.GEValidationProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.GEValidationProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    expectationSuite: msg.getExpectationSuite_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.core.GEValidationProfile}
 */
proto.feast.core.GEValidationProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.core.GEValidationProfile;
  return proto.feast.core.GEValidationProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.core.GEValidationProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.core.GEValidationProfile}
 */
proto.feast.core.GEValidationProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setExpectationSuite(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.core.GEValidationProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.core.GEValidationProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.core.GEValidationProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.GEValidationProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExpectationSuite_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes expectation_suite = 1;
 * @return {string}
 */
proto.feast.core.GEValidationProfile.prototype.getExpectationSuite = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes expectation_suite = 1;
 * This is a type-conversion wrapper around `getExpectationSuite()`
 * @return {string}
 */
proto.feast.core.GEValidationProfile.prototype.getExpectationSuite_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getExpectationSuite()));
};


/**
 * optional bytes expectation_suite = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getExpectationSuite()`
 * @return {!Uint8Array}
 */
proto.feast.core.GEValidationProfile.prototype.getExpectationSuite_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getExpectationSuite()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.feast.core.GEValidationProfile} returns this
 */
proto.feast.core.GEValidationProfile.prototype.setExpectationSuite = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.feast.core.ValidationReference.oneofGroups_ = [[6],[7]];

/**
 * @enum {number}
 */
proto.feast.core.ValidationReference.ProfilerCase = {
  PROFILER_NOT_SET: 0,
  GE_PROFILER: 6
};

/**
 * @return {proto.feast.core.ValidationReference.ProfilerCase}
 */
proto.feast.core.ValidationReference.prototype.getProfilerCase = function() {
  return /** @type {proto.feast.core.ValidationReference.ProfilerCase} */(jspb.Message.computeOneofCase(this, proto.feast.core.ValidationReference.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.feast.core.ValidationReference.CachedProfileCase = {
  CACHED_PROFILE_NOT_SET: 0,
  GE_PROFILE: 7
};

/**
 * @return {proto.feast.core.ValidationReference.CachedProfileCase}
 */
proto.feast.core.ValidationReference.prototype.getCachedProfileCase = function() {
  return /** @type {proto.feast.core.ValidationReference.CachedProfileCase} */(jspb.Message.computeOneofCase(this, proto.feast.core.ValidationReference.oneofGroups_[1]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.feast.core.ValidationReference.prototype.toObject = function(opt_includeInstance) {
  return proto.feast.core.ValidationReference.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.feast.core.ValidationReference} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.ValidationReference.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    referenceDatasetName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    project: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    tagsMap: (f = msg.getTagsMap()) ? f.toObject(includeInstance, undefined) : [],
    geProfiler: (f = msg.getGeProfiler()) && proto.feast.core.GEValidationProfiler.toObject(includeInstance, f),
    geProfile: (f = msg.getGeProfile()) && proto.feast.core.GEValidationProfile.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.feast.core.ValidationReference}
 */
proto.feast.core.ValidationReference.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.feast.core.ValidationReference;
  return proto.feast.core.ValidationReference.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.feast.core.ValidationReference} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.feast.core.ValidationReference}
 */
proto.feast.core.ValidationReference.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReferenceDatasetName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = msg.getTagsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 6:
      var value = new proto.feast.core.GEValidationProfiler;
      reader.readMessage(value,proto.feast.core.GEValidationProfiler.deserializeBinaryFromReader);
      msg.setGeProfiler(value);
      break;
    case 7:
      var value = new proto.feast.core.GEValidationProfile;
      reader.readMessage(value,proto.feast.core.GEValidationProfile.deserializeBinaryFromReader);
      msg.setGeProfile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.feast.core.ValidationReference.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.feast.core.ValidationReference.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.feast.core.ValidationReference} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.feast.core.ValidationReference.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReferenceDatasetName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTagsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getGeProfiler();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.feast.core.GEValidationProfiler.serializeBinaryToWriter
    );
  }
  f = message.getGeProfile();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.feast.core.GEValidationProfile.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.feast.core.ValidationReference.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.core.ValidationReference} returns this
 */
proto.feast.core.ValidationReference.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string reference_dataset_name = 2;
 * @return {string}
 */
proto.feast.core.ValidationReference.prototype.getReferenceDatasetName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.core.ValidationReference} returns this
 */
proto.feast.core.ValidationReference.prototype.setReferenceDatasetName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string project = 3;
 * @return {string}
 */
proto.feast.core.ValidationReference.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.core.ValidationReference} returns this
 */
proto.feast.core.ValidationReference.prototype.setProject = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.feast.core.ValidationReference.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.feast.core.ValidationReference} returns this
 */
proto.feast.core.ValidationReference.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * map<string, string> tags = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.feast.core.ValidationReference.prototype.getTagsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.feast.core.ValidationReference} returns this
 */
proto.feast.core.ValidationReference.prototype.clearTagsMap = function() {
  this.getTagsMap().clear();
  return this;
};


/**
 * optional GEValidationProfiler ge_profiler = 6;
 * @return {?proto.feast.core.GEValidationProfiler}
 */
proto.feast.core.ValidationReference.prototype.getGeProfiler = function() {
  return /** @type{?proto.feast.core.GEValidationProfiler} */ (
    jspb.Message.getWrapperField(this, proto.feast.core.GEValidationProfiler, 6));
};


/**
 * @param {?proto.feast.core.GEValidationProfiler|undefined} value
 * @return {!proto.feast.core.ValidationReference} returns this
*/
proto.feast.core.ValidationReference.prototype.setGeProfiler = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.feast.core.ValidationReference.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.feast.core.ValidationReference} returns this
 */
proto.feast.core.ValidationReference.prototype.clearGeProfiler = function() {
  return this.setGeProfiler(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.feast.core.ValidationReference.prototype.hasGeProfiler = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional GEValidationProfile ge_profile = 7;
 * @return {?proto.feast.core.GEValidationProfile}
 */
proto.feast.core.ValidationReference.prototype.getGeProfile = function() {
  return /** @type{?proto.feast.core.GEValidationProfile} */ (
    jspb.Message.getWrapperField(this, proto.feast.core.GEValidationProfile, 7));
};


/**
 * @param {?proto.feast.core.GEValidationProfile|undefined} value
 * @return {!proto.feast.core.ValidationReference} returns this
*/
proto.feast.core.ValidationReference.prototype.setGeProfile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.feast.core.ValidationReference.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.feast.core.ValidationReference} returns this
 */
proto.feast.core.ValidationReference.prototype.clearGeProfile = function() {
  return this.setGeProfile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.feast.core.ValidationReference.prototype.hasGeProfile = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.feast.core);
